resources:
- repo: self
  clean: true

trigger:
- develop

name: StormCrossLocalization-CI-$(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: windows-latest

steps:
- task: CmdLine@1
  displayName: Cake build
  inputs:
    filename: bash
    arguments: 'build.sh --target release --args.beta=$(Build.BuildId)'
    workingFolder: cake
  condition: and(succeeded(), in(variables['Build.SourceBranch'], 'refs/heads/develop')) 

- task: CmdLine@1
  displayName: Cake build
  inputs:
    filename: bash
    arguments: 'build.sh --target release'
    workingFolder: cake
  condition: and(succeeded(), in(variables['Build.SourceBranch'], 'refs/heads/master')) 

- task: CopyFiles@2
  displayName: "Copy Files to: $(build.artifactstagingdirectory)"
  inputs:
    SourceFolder: artifacts
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: and(succeeded(), in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/develop')) 

- task: PublishBuildArtifacts@1
  displayName: "Publish Artifact: drop"
  condition: and(succeeded(), in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/develop')) 


