version: 1.0.{build}
branches:
  only:
  - develop
  - master
skip_tags: true
image: Visual Studio 2017
before_build:
- cmd: >-
    nuget restore src/StormCrossLocalization.sln
build:
  project: src/StormCrossLocalization.sln
  parallel: true
  verbosity: minimal
test: off