resources:
- repo: self
  clean: true

trigger:
- develop

name: CrossLocalization_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

queue:
  name: Hosted VS2017

steps:
- task: CmdLine@1
  displayName: Cake build
  inputs:
    filename: bash
    arguments: 'build.sh --target release --args.beta=$(Build.BuildId)'
    workingFolder: cake

- task: CopyFiles@2
  displayName: "Copy Files to: $(build.artifactstagingdirectory)"
  inputs:
    SourceFolder: artifacts
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: and(succeeded(), in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/develop')) 

- task: PublishBuildArtifacts@1
  displayName: "Publish Artifact: drop"
  condition: and(succeeded(), in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/develop')) 
