using System;
using System.CodeDom;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Xml;
using Localization.Core;

namespace Localization.WindowsPhone
{
	public class LocalizationWindowsPhoneTask : BaseLocalizationTask
	{
		private const string SERVICE_FILE = Constants.IMPLEMENTATION_SERVICE_NAME + Constants.FILE_SUFFIX;
		private const string LOCALIZED_STRINGS_FILE = Constants.LOCALIZED_STRINGS_NAME + Constants.FILE_SUFFIX;

		protected override void Generate(Dictionary<string, List<ResxFile>> files)
		{
			List<string> keys = new List<string>();

			foreach (string directory in files.Keys)
			{
				GenerateStrings(directory, files[directory]);

				keys.AddRange(files[directory].SelectMany(x => x.Content.Keys.Select(y => y.SimplifyKey())));
			}

			keys = keys.Distinct().ToList();

			GenerateLocalizationService(keys);
			GenerateLocalizedStrings(keys);

			base.Generate(files);
		}

		protected virtual void GenerateStrings(string directory, List<ResxFile> files)
		{
			Dictionary<string, string> content = new Dictionary<string, string>();
			Dictionary<string, string> platformSpecificContent = new Dictionary<string, string>();

			foreach (var item in files.SelectMany(x => x.Content))
			{
				if (item.Key.IsPlatformSpecificString())
				{
					if (item.Key.IsWindowsPhoneString())
					{
						platformSpecificContent.Add(item.Key, item.Value);
					}
				}
				else
				{
					content.Add(item.Key, item.Value);
				}
			}

			foreach (var item in platformSpecificContent)
			{
				string key = item.Key.SimplifyKey();
				if (content.ContainsKey(key))
				{
					content[key] = item.Value;
				}
				else
				{
					content.Add(key, item.Value);
				}
			}

			//write strings.xml file
			XmlDocument document = new XmlDocument();
			document.AppendChild(document.CreateXmlDeclaration("1.0", "utf-8", null));
			XmlNode rootNode = document.CreateElement("root");
			document.AppendChild(rootNode);
			rootNode.AppendChild(document.CreateComment("This file was generated by Localization task for Windows Phone"));

			//headers
			Dictionary<string, string> headers = new Dictionary<string, string>
			{
				["resmimetype"] = "text/microsoft-resx",
				["version"] = "2.0",
				["reader"] = "System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
				["writer"] = "System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"
			};

			foreach (var header in headers)
			{
				XmlElement resHeader = document.CreateElement("resheader");
				XmlAttribute nameAttribute = document.CreateAttribute("name");
				nameAttribute.Value = header.Key;
				resHeader.Attributes.Append(nameAttribute);

				XmlElement value = document.CreateElement("value");
				value.InnerText = header.Value;

				resHeader.AppendChild(value);
				rootNode.AppendChild(resHeader);
			}

			foreach (var pair in content)
			{
				XmlElement data = document.CreateElement("data");
				XmlAttribute nameAttribute = document.CreateAttribute("name");
				nameAttribute.Value = pair.Key;
				data.Attributes.Append(nameAttribute);

				XmlElement value = document.CreateElement("value");
				value.InnerText = pair.Value;

				data.AppendChild(value);
				rootNode.AppendChild(data);
			}

			document.Save(Path.Combine(directory, "Resources.resw"));
		}

		protected virtual void GenerateLocalizationService(List<string> keys)
		{
			CodeCompileUnit codeUnit = new CodeCompileUnit();

			// for class declaration
			CodeNamespace codeNamespace = new CodeNamespace(GenerationNamespace);
			codeUnit.Namespaces.Add(codeNamespace);

			codeNamespace.Imports.Add(new CodeNamespaceImport("Windows.ApplicationModel.Resources"));
			
			// create class
			CodeTypeDeclaration classDeclaration = new CodeTypeDeclaration(Constants.IMPLEMENTATION_SERVICE_NAME)
			{
				IsClass = true,
				TypeAttributes = TypeAttributes.Public,
			};
			classDeclaration.BaseTypes.Add(Constants.INTERFACE_SERVICE_NAME);
			codeNamespace.Types.Add(classDeclaration);

			const string fieldName = "_res";

			//field
			CodeMemberField field = new CodeMemberField("ResourceLoader", fieldName)
			{
				Attributes = MemberAttributes.Private
			};
			classDeclaration.Members.Add(field);

			//constructor
			CodeConstructor constructor = new CodeConstructor
			{
				Attributes = MemberAttributes.Public
			};
			constructor.Parameters.Add(new CodeParameterDeclarationExpression("ResourceLoader", "res"));
			constructor.Statements.Add(new CodeAssignStatement(new CodeFieldReferenceExpression(new CodeThisReferenceExpression(), fieldName), new CodeVariableReferenceExpression("res")));
			classDeclaration.Members.Add(constructor);

			//methode
			var method = new CodeMemberMethod
			{
				Name = Constants.SERVICE_METHOD_NAME,
				ReturnType = new CodeTypeReference(typeof(string)),
				Attributes = MemberAttributes.Public
			};
			method.Parameters.Add(new CodeParameterDeclarationExpression(Constants.ENUM_NAME, "key"));
			classDeclaration.Members.Add(method);

			CodeVariableReferenceExpression methodParam = new CodeVariableReferenceExpression("key");
			CodeFieldReferenceExpression contextReference = new CodeFieldReferenceExpression(new CodeThisReferenceExpression(), fieldName);
			CodeMethodReferenceExpression getStringMethod = new CodeMethodReferenceExpression(contextReference, "GetString");
			
			foreach (string key in keys)
			{
				CodeConditionStatement condition = new CodeConditionStatement(
					new CodeBinaryOperatorExpression(
						methodParam,
						CodeBinaryOperatorType.IdentityEquality,
						new CodePropertyReferenceExpression(new CodeVariableReferenceExpression(Constants.ENUM_NAME), key)
						),
					new CodeMethodReturnStatement(
						new CodeMethodInvokeExpression(getStringMethod, new CodePrimitiveExpression(key.UnprocessKey()))
						)
					);

				method.Statements.Add(condition);
			}

			method.Statements.Add(new CodeThrowExceptionStatement(new CodeObjectCreateExpression(typeof(ArgumentOutOfRangeException))));

			codeUnit.WriteToFile(SERVICE_FILE, "This file was generated by Localization task for WindowsPhone");
		}

		protected virtual void GenerateLocalizedStrings(List<string> keys)
		{
			CodeCompileUnit codeUnit = new CodeCompileUnit();

			// for class declaration
			CodeNamespace codeNamespace = new CodeNamespace(GenerationNamespace);
			codeUnit.Namespaces.Add(codeNamespace);

			codeNamespace.Imports.Add(new CodeNamespaceImport("Windows.ApplicationModel.Resources"));

			// create class
			CodeTypeDeclaration classDeclaration = new CodeTypeDeclaration(Constants.LOCALIZED_STRINGS_NAME)
			{
				IsClass = true,
				TypeAttributes = TypeAttributes.Public | TypeAttributes.Sealed,
			};
			codeNamespace.Types.Add(classDeclaration);

			const string fieldName = "_res";

			//field
			CodeMemberField field = new CodeMemberField("ResourceLoader", fieldName)
			{
				Attributes = MemberAttributes.Private | MemberAttributes.Static
			};
			classDeclaration.Members.Add(field);

			//initialize method
			CodeMemberMethod initializeMethod = new CodeMemberMethod
			{
				Name = "Initialize",
				Attributes = MemberAttributes.Public | MemberAttributes.Static
			};
			initializeMethod.Parameters.Add(new CodeParameterDeclarationExpression("ResourceLoader", "res"));
			initializeMethod.Statements.Add(new CodeAssignStatement(new CodeFieldReferenceExpression(new CodeTypeReferenceExpression(Constants.LOCALIZED_STRINGS_NAME), fieldName), new CodeVariableReferenceExpression("res")));
			classDeclaration.Members.Add(initializeMethod);

			//constructor
			CodeConstructor constructor = new CodeConstructor
			{
				Attributes = MemberAttributes.Private
			};
			classDeclaration.Members.Add(constructor);

			CodeFieldReferenceExpression contextReference = new CodeFieldReferenceExpression(new CodeTypeReferenceExpression(Constants.LOCALIZED_STRINGS_NAME), fieldName);
			CodeMethodReferenceExpression getStringMethod = new CodeMethodReferenceExpression(contextReference, "GetString");
			
			//properties
			foreach (string key in keys)
			{
				CodeMemberProperty property = new CodeMemberProperty
				{
					Name = key,
					Type = new CodeTypeReference(typeof(string)),
					Attributes = MemberAttributes.Public | MemberAttributes.Static
				};

				property.GetStatements.Add(new CodeMethodReturnStatement(
					new CodeMethodInvokeExpression(getStringMethod, new CodePrimitiveExpression(key.UnprocessKey()))
					));
				classDeclaration.Members.Add(property);
			}

			codeUnit.WriteToFile(LOCALIZED_STRINGS_FILE, "This file was generated by Localization task for WindowsPhone");
		}
	}
}
